-- Core Copilot agent (temporarily disabled)
-- return {
--   'zbirenbaum/copilot.lua',
--   cmd = 'Copilot',
--   event = 'InsertEnter',
--   build = ':Copilot auth',
--   config = function()
--     require('copilot').setup {
--       suggestion = { enabled = false },
--       panel = { enabled = false },
--     }
--   end,
-- }
return {}
